[programs.localnet]
mango_blender = "6iwLfHKbjvrmQ9jSWAvVu1C8zdWReX2s8XX9yFmvM6p5"

[programs.devnet]
mango_blender = "6iwLfHKbjvrmQ9jSWAvVu1C8zdWReX2s8XX9yFmvM6p5"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/jarettdunn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[[test.genesis]]
address = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFin"
program = "./tests/fixtures/serum_dex.so"

[[test.genesis]]
address = "mv3ekLzLbnVPNxjSKvqBpU3ZeZXPQdEC3bp5MDEBG68"
program = "./tests/fixtures/mango.so"